### ISSUE TITLE
导入的XML内容排序不理想

### ISSUE THREAD

**Issue by dhammavipassi** [Zacharia2/SuperMemo-Toolkit#26]
使用Calibre将PDF文档转换成Epub格式，再通过power shell 将其转换成XML，导入到 SuperMemo 后，文字的排列如下。不知道是什么原因造成的，求救！
![Uploading Screenshot 2024-02-29 at 11.39.16 AM.png…]()

**Comment by dhammavipassi** [comment]
<img width="1094" alt="Screenshot 2024-02-29 at 11 39 16 AM" src="https://github.com/Zacharia2/SuperMemo-Toolkit/assets/127640726/ca6e54e9-dfb1-4879-bc10-3f20b63f16df">

**Comment by Zacharia2** [comment]
信息太少

**Comment by dhammavipassi** [comment]
大概率就是calibre将PDF转换成Epub过程中，Epub保留了PDF原来的文字段落排版样式，Epub转成XML，也引用了这个排版。我尝试PDF转换成Epub步骤中，在Calibre中调整了一系列参数，还是无法改变输出的Epub，最终这个方案只能搁置了。如果作者在将pdf转换成epub的过程中有什么经验，可以分享一下。或者在Epub转成XML过程中，能够调整内容适应SuperMemo阅读也好。

**Comment by Zacharia2** [comment]
可能只是pdf转epub之后，需要自己在修改这个epub的目录吧。其实对于pdf，建议使用“`smtk e2sm -l epub_file out_folder`  #（有书即可，按照图书文档文件的线性顺序生成）”这个命令

**Comment by Zacharia2** [comment]
![image](https://github.com/Zacharia2/SuperMemo-Toolkit/assets/32425955/1f5dca0c-5fdd-4043-a2e1-e911eb0c0ea9)

**Comment by Zacharia2** [comment]
还有就是，要把生成的图片文件夹放到指定目录。

**Comment by Zacharia2** [comment]
对于全图片的epub，排版啥的就不要太追求了，能看就行。
