### ISSUE TITLE
supermemo_toolkit-py3-none-any.whl does not exist

### ISSUE THREAD

**Issue by 6jiaxi0** [Zacharia2/SuperMemo-Toolkit#28]
我在跟着install的过程中，出现了一些问题，首先就是通过python3 -m pip install --user pipx安装后，找不到pipx.exe，然后我就 使用Scooop下载了pipx，接着接下来的下载步骤，就出现了“不存在”这个问题，是不是第三步 要下载那个whl格式的文件，但是我没找到，小白在线求解
![image](https://github.com/user-attachments/assets/ee923498-53ed-4b3e-8773-aa2bce2a8ffb)

**Comment by Zacharia2** [comment]
whl软件包在release页面里面可以下载
